runtime:
  version: "test"
  name: "" # will be overrriden
  PJRT_DEVICE: CUDA

opt:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.0

train:
    batch_size: 128
    shuffle: True
    num_workers: 4
    pin_memory: True
    drop_last: True

val:
    batch_size: 128
    drop_last: False
    shuffle: False
    num_workers: 4
    pin_memory: True

context_type:
    _target_: context.ContextDummy
    idim: 1024
    odim: 128
    
defaults:
  - model: dust3r
  - probe: linear
  - loss: cross_entropy
  - metrics: seg
  
