# coding=utf-8
# Copyright 2026 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import torch
import torch.nn as nn
import torch.nn.functional as F

def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class CrossAttention(nn.Module):

    def __init__(self, dim, num_heads=8, qkv_bias=False, attn_drop=0., proj_drop=0.):
        super().__init__()
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = head_dim ** -0.5

        self.projq = nn.Linear(dim, dim, bias=qkv_bias)
        self.projk = nn.Linear(dim, dim, bias=qkv_bias)
        self.projv = nn.Linear(dim, dim, bias=qkv_bias)
        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = nn.Linear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    #@torch.compile
    def forward(self, query, key, value):
        B, Nq, C = query.shape
        Nk = key.shape[1]
        Nv = value.shape[1]

        q = self.projq(query).reshape(B,Nq,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)
        k = self.projk(key).reshape(B,Nk,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)
        v = self.projv(value).reshape(B,Nv,self.num_heads, C// self.num_heads).permute(0, 2, 1, 3)

        x = F.scaled_dot_product_attention(
                q, k, v,
                dropout_p=self.attn_drop.p if self.training else 0.,
        )

        x = x.transpose(1, 2).reshape(B, Nq, C)
        x = self.proj(x)
        x = self.proj_drop(x)

        return x

class CrossAttentionProbe(nn.Module):

    def __init__(self, dim, num_queries, with_norm=False, downscale=1):
        super().__init__()

        self.queries = nn.Parameter(torch.randn(1, num_queries, dim))
        self.downscale = downscale

        self.cross_attn = CrossAttention(dim)

        self.norm = nn.LayerNorm(dim) if with_norm else nn.Identity()
        self.norm1 = nn.LayerNorm(dim) if with_norm else nn.Identity()
        self.norm2 = nn.LayerNorm(dim) if with_norm else nn.Identity()

    def forward(self, x_orig):
        B,C,H,W = x_orig.shape

        Hx = H // self.downscale
        Wx = W // self.downscale

        x = F.interpolate(x_orig, (Hx, Wx), mode="bilinear")
        x = x.flatten(-2).movedim(1, -1)
        x_norm = self.norm(x)

        queries = self.norm1(self.queries).repeat(B, 1, 1)

        y = self.cross_attn(queries, x_norm, x_norm)
        y = self.norm2(y)

        xo = x_orig.flatten(-2).movedim(1, -1)
        xo = self.norm(xo)

        z = torch.einsum('bnd,bkd->bkn', xo, y) #/ C**2
        z = z.unflatten(-1, (H, W))

        return z

class AttentionProbe(nn.Module):

    def __init__(
            self,
            cfg,
            idim_enc,
            idim_dec,
            odim,
            with_norm=False,
            downscale=4
    ):
        super().__init__()

        self.alpha_enc = cfg.alpha_enc
        self.alpha_dec = cfg.alpha_dec

        self.with_norm = with_norm
        self.downscale = downscale

        self.probe_enc = nn.Conv2d(idim_enc, odim, 1)
        self.probe_dec = CrossAttentionProbe(idim_dec, odim, with_norm, downscale)

    def parameters(self):
        return list(self.probe_dec.parameters()) + \
                list(self.probe_enc.parameters())

    def forward(self, feats_enc, feats_dec, scale_to):

        # encoder features
        #feats_dec_lr = F.adaptive_avg_pool2d(feats_dec, (64, 64))
        #logits_enc = self.probe_dec_LR(feats_dec_lr)

        logits = self.probe_enc(feats_enc)
        logits = self.alpha_enc * F.interpolate(logits, scale_to, mode="bilinear", align_corners=False)

        if self.alpha_dec > 0.:
            # decoder features
            logits_dec = self.probe_dec(F.relu(feats_dec))
            if logits_dec.shape[-2:] != scale_to:
                #print(f"Decoder resampling {logits_dec.shape[-2:]} to {scale_to}")
                logits_dec = F.interpolate(logits_dec, scale_to, mode="bilinear", align_corners=False)

            logits += self.alpha_dec * logits_dec

        return logits